[package]
name = "soundyrust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
augmented-midi = "1.8.0"
helgoboss-midi = "0.4.0"
itertools = "0.13.0"
rustysynth = "1.3.2"

[lib]
name = "soundyrust"
path = "src/lib.rs"
